# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  video-deployment
  namespace: app-space
  labels:
    app:  video
spec:
  selector:
    matchLabels:
      app: video
  replicas: 1
  template:
    metadata:
      labels:
        app: video
    spec:
       containers:
        - image:  kodekloud/ecommerce:video
          name:  video
          ports:
            - containerPort: 8080
    