# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  default-backend
  namespace: app-space
  
spec:
  selector:
    matchLabels:
      app: default-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: default-backend
    spec:
       containers:
        - name: default 
          image:  kodekloud/ecommerce:404
          ports:
            - containerPort: 8080
    