# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wear-deployment
  namespace: app-space
  labels:
    app:  wear
spec:
  selector:
    matchLabels:
      app: wear
  replicas: 1
  template:
    metadata:
      labels:
        app: wear
    spec:
       containers:
        - image:  kodekloud/ecommerce:apparels
          name:  wear
          ports:
            - containerPort: 8080
    